// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cinema.ext.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CinemaServiceExt service

func NewCinemaServiceExtEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CinemaServiceExt service

type CinemaServiceExtService interface {
	// 地点影城
	LocationCinema(ctx context.Context, in *LocationCinemaReq, opts ...client.CallOption) (*LocationCinemaRsp, error)
	// 根据位置查看有销售对应电影的影院信息
	// rpc GetCinemaMessage(GetCinemaMessageReq) returns(GetCinemaMessageRsp) {}
	// 根据id查看影院的信息和即将上映的影片信息
	GetCinemaMessageByCid(ctx context.Context, in *GetCinemaMessageByCidReq, opts ...client.CallOption) (*GetCinemaMessageByCidRsp, error)
	// 根据mh_id获取影厅信息
	GetMovieHallByMHId(ctx context.Context, in *GetMovieHallByMHIdReq, opts ...client.CallOption) (*GetMovieHallByMHIdRsp, error)
}

type cinemaServiceExtService struct {
	c    client.Client
	name string
}

func NewCinemaServiceExtService(name string, c client.Client) CinemaServiceExtService {
	return &cinemaServiceExtService{
		c:    c,
		name: name,
	}
}

func (c *cinemaServiceExtService) LocationCinema(ctx context.Context, in *LocationCinemaReq, opts ...client.CallOption) (*LocationCinemaRsp, error) {
	req := c.c.NewRequest(c.name, "CinemaServiceExt.LocationCinema", in)
	out := new(LocationCinemaRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaServiceExtService) GetCinemaMessageByCid(ctx context.Context, in *GetCinemaMessageByCidReq, opts ...client.CallOption) (*GetCinemaMessageByCidRsp, error) {
	req := c.c.NewRequest(c.name, "CinemaServiceExt.GetCinemaMessageByCid", in)
	out := new(GetCinemaMessageByCidRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaServiceExtService) GetMovieHallByMHId(ctx context.Context, in *GetMovieHallByMHIdReq, opts ...client.CallOption) (*GetMovieHallByMHIdRsp, error) {
	req := c.c.NewRequest(c.name, "CinemaServiceExt.GetMovieHallByMHId", in)
	out := new(GetMovieHallByMHIdRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CinemaServiceExt service

type CinemaServiceExtHandler interface {
	// 地点影城
	LocationCinema(context.Context, *LocationCinemaReq, *LocationCinemaRsp) error
	// 根据位置查看有销售对应电影的影院信息
	// rpc GetCinemaMessage(GetCinemaMessageReq) returns(GetCinemaMessageRsp) {}
	// 根据id查看影院的信息和即将上映的影片信息
	GetCinemaMessageByCid(context.Context, *GetCinemaMessageByCidReq, *GetCinemaMessageByCidRsp) error
	// 根据mh_id获取影厅信息
	GetMovieHallByMHId(context.Context, *GetMovieHallByMHIdReq, *GetMovieHallByMHIdRsp) error
}

func RegisterCinemaServiceExtHandler(s server.Server, hdlr CinemaServiceExtHandler, opts ...server.HandlerOption) error {
	type cinemaServiceExt interface {
		LocationCinema(ctx context.Context, in *LocationCinemaReq, out *LocationCinemaRsp) error
		GetCinemaMessageByCid(ctx context.Context, in *GetCinemaMessageByCidReq, out *GetCinemaMessageByCidRsp) error
		GetMovieHallByMHId(ctx context.Context, in *GetMovieHallByMHIdReq, out *GetMovieHallByMHIdRsp) error
	}
	type CinemaServiceExt struct {
		cinemaServiceExt
	}
	h := &cinemaServiceExtHandler{hdlr}
	return s.Handle(s.NewHandler(&CinemaServiceExt{h}, opts...))
}

type cinemaServiceExtHandler struct {
	CinemaServiceExtHandler
}

func (h *cinemaServiceExtHandler) LocationCinema(ctx context.Context, in *LocationCinemaReq, out *LocationCinemaRsp) error {
	return h.CinemaServiceExtHandler.LocationCinema(ctx, in, out)
}

func (h *cinemaServiceExtHandler) GetCinemaMessageByCid(ctx context.Context, in *GetCinemaMessageByCidReq, out *GetCinemaMessageByCidRsp) error {
	return h.CinemaServiceExtHandler.GetCinemaMessageByCid(ctx, in, out)
}

func (h *cinemaServiceExtHandler) GetMovieHallByMHId(ctx context.Context, in *GetMovieHallByMHIdReq, out *GetMovieHallByMHIdRsp) error {
	return h.CinemaServiceExtHandler.GetMovieHallByMHId(ctx, in, out)
}
