// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc2
// source: comment.ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HotCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId int64 `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
}

func (x *HotCommentReq) Reset() {
	*x = HotCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotCommentReq) ProtoMessage() {}

func (x *HotCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotCommentReq.ProtoReflect.Descriptor instead.
func (*HotCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{0}
}

func (x *HotCommentReq) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type HotCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CommentData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HotCommentRsp) Reset() {
	*x = HotCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotCommentRsp) ProtoMessage() {}

func (x *HotCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotCommentRsp.ProtoReflect.Descriptor instead.
func (*HotCommentRsp) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{1}
}

func (x *HotCommentRsp) GetData() *CommentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mini *CommentMini `protobuf:"bytes,1,opt,name=mini,proto3" json:"mini,omitempty"`
	Plus *CommentPlus `protobuf:"bytes,2,opt,name=plus,proto3" json:"plus,omitempty"`
}

func (x *CommentData) Reset() {
	*x = CommentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentData) ProtoMessage() {}

func (x *CommentData) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentData.ProtoReflect.Descriptor instead.
func (*CommentData) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{2}
}

func (x *CommentData) GetMini() *CommentMini {
	if x != nil {
		return x.Mini
	}
	return nil
}

func (x *CommentData) GetPlus() *CommentPlus {
	if x != nil {
		return x.Plus
	}
	return nil
}

type CommentMini struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*CommentRecord `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CommentMini) Reset() {
	*x = CommentMini{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentMini) ProtoMessage() {}

func (x *CommentMini) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentMini.ProtoReflect.Descriptor instead.
func (*CommentMini) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{3}
}

func (x *CommentMini) GetList() []*CommentRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CommentMini) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentPlus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*CommentRecord `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CommentPlus) Reset() {
	*x = CommentPlus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentPlus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPlus) ProtoMessage() {}

func (x *CommentPlus) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPlus.ProtoReflect.Descriptor instead.
func (*CommentPlus) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{4}
}

func (x *CommentPlus) GetList() []*CommentRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CommentPlus) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	HeadImg   string `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Nickname  string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreateAt  string `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpNum     int64  `protobuf:"varint,6,opt,name=upNum,proto3" json:"upNum,omitempty"`
	CommentID int64  `protobuf:"varint,7,opt,name=commentID,proto3" json:"commentID,omitempty"`
}

func (x *CommentRecord) Reset() {
	*x = CommentRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRecord) ProtoMessage() {}

func (x *CommentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRecord.ProtoReflect.Descriptor instead.
func (*CommentRecord) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{5}
}

func (x *CommentRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommentRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentRecord) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

func (x *CommentRecord) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommentRecord) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *CommentRecord) GetUpNum() int64 {
	if x != nil {
		return x.UpNum
	}
	return 0
}

func (x *CommentRecord) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

type MakeCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId  int64  `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"` // 影片id
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`      // 标题
	HeadImg  string `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"` // 用户昵称
	UserId   int64  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`    // 用户id
	Content  string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MakeCommentReq) Reset() {
	*x = MakeCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCommentReq) ProtoMessage() {}

func (x *MakeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCommentReq.ProtoReflect.Descriptor instead.
func (*MakeCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{6}
}

func (x *MakeCommentReq) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *MakeCommentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MakeCommentReq) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

func (x *MakeCommentReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *MakeCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MakeCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MakeCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeCommentRsp) Reset() {
	*x = MakeCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCommentRsp) ProtoMessage() {}

func (x *MakeCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCommentRsp.ProtoReflect.Descriptor instead.
func (*MakeCommentRsp) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{7}
}

type UpNumCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentID int64 `protobuf:"varint,1,opt,name=commentID,proto3" json:"commentID,omitempty"`
}

func (x *UpNumCommentReq) Reset() {
	*x = UpNumCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpNumCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpNumCommentReq) ProtoMessage() {}

func (x *UpNumCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpNumCommentReq.ProtoReflect.Descriptor instead.
func (*UpNumCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{8}
}

func (x *UpNumCommentReq) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

type UpNumCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpNum int64 `protobuf:"varint,1,opt,name=upNum,proto3" json:"upNum,omitempty"`
}

func (x *UpNumCommentRsp) Reset() {
	*x = UpNumCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpNumCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpNumCommentRsp) ProtoMessage() {}

func (x *UpNumCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpNumCommentRsp.ProtoReflect.Descriptor instead.
func (*UpNumCommentRsp) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{9}
}

func (x *UpNumCommentRsp) GetUpNum() int64 {
	if x != nil {
		return x.UpNum
	}
	return 0
}

type MyCommentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MyCommentsReq) Reset() {
	*x = MyCommentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCommentsReq) ProtoMessage() {}

func (x *MyCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCommentsReq.ProtoReflect.Descriptor instead.
func (*MyCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{10}
}

func (x *MyCommentsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MyCommentsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyComments []*MyComment `protobuf:"bytes,1,rep,name=myComments,proto3" json:"myComments,omitempty"`
}

func (x *MyCommentsRsp) Reset() {
	*x = MyCommentsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyCommentsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCommentsRsp) ProtoMessage() {}

func (x *MyCommentsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCommentsRsp.ProtoReflect.Descriptor instead.
func (*MyCommentsRsp) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{11}
}

func (x *MyCommentsRsp) GetMyComments() []*MyComment {
	if x != nil {
		return x.MyComments
	}
	return nil
}

type MyComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmImage string `protobuf:"bytes,1,opt,name=filmImage,proto3" json:"filmImage,omitempty"`
	FilmName  string `protobuf:"bytes,2,opt,name=filmName,proto3" json:"filmName,omitempty"`
	Score     string `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	CommentID int64  `protobuf:"varint,4,opt,name=commentID,proto3" json:"commentID,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	UpNum     int64  `protobuf:"varint,6,opt,name=upNum,proto3" json:"upNum,omitempty"`
}

func (x *MyComment) Reset() {
	*x = MyComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyComment) ProtoMessage() {}

func (x *MyComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyComment.ProtoReflect.Descriptor instead.
func (*MyComment) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{12}
}

func (x *MyComment) GetFilmImage() string {
	if x != nil {
		return x.FilmImage
	}
	return ""
}

func (x *MyComment) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *MyComment) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *MyComment) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

func (x *MyComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MyComment) GetUpNum() int64 {
	if x != nil {
		return x.UpNum
	}
	return 0
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentID int64 `protobuf:"varint,1,opt,name=commentID,proto3" json:"commentID,omitempty"`
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCommentReq) GetCommentID() int64 {
	if x != nil {
		return x.CommentID
	}
	return 0
}

type DeleteCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentRsp) Reset() {
	*x = DeleteCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comment_ext_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRsp) ProtoMessage() {}

func (x *DeleteCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_ext_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRsp.ProtoReflect.Descriptor instead.
func (*DeleteCommentRsp) Descriptor() ([]byte, []int) {
	return file_comment_ext_proto_rawDescGZIP(), []int{14}
}

var File_comment_ext_proto protoreflect.FileDescriptor

var file_comment_ext_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x48, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x31,
	0x0a, 0x0d, 0x48, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x51, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x20, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x69, 0x6e, 0x69, 0x52, 0x04, 0x6d, 0x69,
	0x6e, 0x69, 0x12, 0x20, 0x0a, 0x04, 0x70, 0x6c, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x75, 0x73, 0x52, 0x04,
	0x70, 0x6c, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x69, 0x6e, 0x69, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x47, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xc5, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x49, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49,
	0x6d, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x70,
	0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x70, 0x4e, 0x75, 0x6d,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0xa8,
	0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x61, 0x6b,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x2f, 0x0a, 0x0f, 0x55,
	0x70, 0x4e, 0x75, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x0f,
	0x55, 0x70, 0x4e, 0x75, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x75, 0x70, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x75, 0x70, 0x4e, 0x75, 0x6d, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b,
	0x0a, 0x0d, 0x4d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x0a, 0x6d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0a, 0x6d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x09,
	0x4d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x6d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x6c, 0x6d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x70, 0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x75, 0x70, 0x4e, 0x75, 0x6d, 0x22, 0x30, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x32, 0x95, 0x02,
	0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x45, 0x78, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x48, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x2e, 0x48, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x48, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0b, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x55, 0x70, 0x4e, 0x75, 0x6d, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x2e, 0x55, 0x70, 0x4e, 0x75, 0x6d, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x55, 0x70, 0x4e, 0x75, 0x6d,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a,
	0x4d, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x2e, 0x4d, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x4d, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comment_ext_proto_rawDescOnce sync.Once
	file_comment_ext_proto_rawDescData = file_comment_ext_proto_rawDesc
)

func file_comment_ext_proto_rawDescGZIP() []byte {
	file_comment_ext_proto_rawDescOnce.Do(func() {
		file_comment_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_comment_ext_proto_rawDescData)
	})
	return file_comment_ext_proto_rawDescData
}

var file_comment_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_comment_ext_proto_goTypes = []interface{}{
	(*HotCommentReq)(nil),    // 0: HotCommentReq
	(*HotCommentRsp)(nil),    // 1: HotCommentRsp
	(*CommentData)(nil),      // 2: CommentData
	(*CommentMini)(nil),      // 3: CommentMini
	(*CommentPlus)(nil),      // 4: CommentPlus
	(*CommentRecord)(nil),    // 5: CommentRecord
	(*MakeCommentReq)(nil),   // 6: MakeCommentReq
	(*MakeCommentRsp)(nil),   // 7: MakeCommentRsp
	(*UpNumCommentReq)(nil),  // 8: UpNumCommentReq
	(*UpNumCommentRsp)(nil),  // 9: UpNumCommentRsp
	(*MyCommentsReq)(nil),    // 10: MyCommentsReq
	(*MyCommentsRsp)(nil),    // 11: MyCommentsRsp
	(*MyComment)(nil),        // 12: MyComment
	(*DeleteCommentReq)(nil), // 13: DeleteCommentReq
	(*DeleteCommentRsp)(nil), // 14: DeleteCommentRsp
}
var file_comment_ext_proto_depIdxs = []int32{
	2,  // 0: HotCommentRsp.data:type_name -> CommentData
	3,  // 1: CommentData.mini:type_name -> CommentMini
	4,  // 2: CommentData.plus:type_name -> CommentPlus
	5,  // 3: CommentMini.list:type_name -> CommentRecord
	5,  // 4: CommentPlus.list:type_name -> CommentRecord
	12, // 5: MyCommentsRsp.myComments:type_name -> MyComment
	0,  // 6: CommentServiceExt.HotComment:input_type -> HotCommentReq
	6,  // 7: CommentServiceExt.MakeComment:input_type -> MakeCommentReq
	8,  // 8: CommentServiceExt.UpNumComment:input_type -> UpNumCommentReq
	10, // 9: CommentServiceExt.MyComments:input_type -> MyCommentsReq
	13, // 10: CommentServiceExt.DeleteComment:input_type -> DeleteCommentReq
	1,  // 11: CommentServiceExt.HotComment:output_type -> HotCommentRsp
	7,  // 12: CommentServiceExt.MakeComment:output_type -> MakeCommentRsp
	9,  // 13: CommentServiceExt.UpNumComment:output_type -> UpNumCommentRsp
	11, // 14: CommentServiceExt.MyComments:output_type -> MyCommentsRsp
	14, // 15: CommentServiceExt.DeleteComment:output_type -> DeleteCommentRsp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_comment_ext_proto_init() }
func file_comment_ext_proto_init() {
	if File_comment_ext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comment_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentMini); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentPlus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpNumCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpNumCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyCommentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyCommentsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comment_ext_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comment_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_ext_proto_goTypes,
		DependencyIndexes: file_comment_ext_proto_depIdxs,
		MessageInfos:      file_comment_ext_proto_msgTypes,
	}.Build()
	File_comment_ext_proto = out.File
	file_comment_ext_proto_rawDesc = nil
	file_comment_ext_proto_goTypes = nil
	file_comment_ext_proto_depIdxs = nil
}
